# Generated by Django 3.2.6 on 2023-03-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='historias.historia')),
            ],
        ),
    ]
