# Generated by Django 3.0.4 on 2023-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
